/* V1.13/V1.14 — GEI Learning Streak Rewards, Achievements & Vault */
(() => {
  "use strict";
  const STORAGE_KEY = "geiAcademyAchievementsV1";
  const ACHIEVEMENTS = [
    { days: 2, name: "First Spark", icon: "✦", reward: 25, message: "Two learning days in a row." },
    { days: 3, name: "Flow Builder", icon: "💧", reward: 50, message: "Three days of GEI momentum." },
    { days: 5, name: "Dam Builder", icon: "⚙", reward: 75, message: "Five days of sustained learning." },
    { days: 6, name: "Blueprint Master", icon: "🏆", reward: 100, message: "The full six-day rhythm achieved." }
  ];
  const DEFAULT_STATE = { earned: [], totalRewards: 0, lastEarned: null };
  let state = loadState();
  function loadState(){try{const p=JSON.parse(localStorage.getItem(STORAGE_KEY)||"null");if(!p)return {...DEFAULT_STATE};return {earned:[...new Set((Array.isArray(p.earned)?p.earned:[]).map(Number).filter(n=>ACHIEVEMENTS.some(a=>a.days===n)))],totalRewards:Math.max(0,Number(p.totalRewards)||0),lastEarned:Number(p.lastEarned)||null};}catch(e){return {...DEFAULT_STATE};}}
  function saveState(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(state));}catch(e){}}
  function markup(){return `<section class="gei-achievement-card" id="gei-achievement-card" aria-labelledby="gei-achievement-title"><div class="gei-achievement-top"><div><span class="gei-achievement-kicker">STREAK ACHIEVEMENTS</span><h2 class="gei-achievement-title" id="gei-achievement-title">Learning Rewards</h2></div><span class="gei-achievement-count" id="gei-achievement-count">0 / 4</span></div><div class="gei-achievement-grid" aria-label="GEI streak achievements">${ACHIEVEMENTS.map(a=>`<div class="gei-achievement" data-achievement-days="${a.days}"><span class="gei-achievement-icon" aria-hidden="true">${a.icon}</span><span class="gei-achievement-name">${a.days}-DAY ${a.name}</span><span class="gei-achievement-reward">+${a.reward} XP</span></div>`).join("")}</div><p class="gei-achievement-status" id="gei-achievement-status">Build your streak to unlock your first reward.</p><div class="gei-achievement-toast" id="gei-achievement-toast" role="status" aria-live="polite"><span class="gei-achievement-toast-icon" id="gei-achievement-toast-icon">🏆</span><span class="gei-achievement-toast-copy"><strong id="gei-achievement-toast-title">Achievement earned!</strong><span id="gei-achievement-toast-message"></span></span><span class="gei-achievement-toast-xp" id="gei-achievement-toast-xp"></span></div></section>`;}
  function ensureCard(){return;}
  function render(){ensureCard();const c=document.getElementById("gei-achievement-card");if(!c)return;const earned=new Set(state.earned);c.querySelectorAll(".gei-achievement").forEach(e=>e.classList.toggle("is-earned",earned.has(Number(e.dataset.achievementDays))));const count=c.querySelector("#gei-achievement-count");if(count)count.textContent=`${state.earned.length} / ${ACHIEVEMENTS.length}`;const status=c.querySelector("#gei-achievement-status");if(status)status.textContent=state.earned.length?`${state.earned.length} achievement${state.earned.length===1?"":"s"} earned • ${state.totalRewards} XP from streak rewards.`:"Build your streak to unlock your first reward.";}
  function showToast(a){const t=document.getElementById("gei-achievement-toast");if(!t)return;document.getElementById("gei-achievement-toast-icon").textContent=a.icon;document.getElementById("gei-achievement-toast-title").textContent=`${a.days}-Day Achievement Earned!`;document.getElementById("gei-achievement-toast-message").textContent=a.message;document.getElementById("gei-achievement-toast-xp").textContent=`+${a.reward} XP`;t.classList.add("is-visible");window.setTimeout(()=>t.classList.remove("is-visible"),4200);}
  function evaluate(detail){const streak=Number(detail?.streak)||0;if(!streak)return;const a=ACHIEVEMENTS.find(x=>x.days===streak&&!state.earned.includes(x.days));if(!a)return;state.earned.push(a.days);state.earned=[...new Set(state.earned)].sort((x,y)=>x-y);state.totalRewards+=a.reward;state.lastEarned=a.days;saveState();render();/* V1.63: streak achievements are badges; they do not grant XP. */showToast(a);window.dispatchEvent(new CustomEvent("gei:achievement-earned",{detail:{...a,totalRewards:state.totalRewards}}));const m=document.querySelector("#home-adam-assistant-message");if(m)m.textContent=`Achievement unlocked: ${a.days}-day ${a.name}. You earned +${a.reward} XP. Keep building your GEI rhythm.`;}
  function loadVault(){if(document.querySelector('script[data-gei-vault-engine]'))return;const s=document.createElement("script");s.src="vault.js";s.defer=true;s.dataset.geiVaultEngine="true";document.head.appendChild(s);const c=document.createElement("link");c.rel="stylesheet";c.href="vault.css";document.head.appendChild(c);}
  function init(){render();window.addEventListener("gei:streak-updated",e=>evaluate(e.detail));window.addEventListener("gei:progress-ready",render);window.GEI_ACHIEVEMENTS=Object.freeze({getState:()=>({...state}),getAchievements:()=>ACHIEVEMENTS.map(a=>({...a,earned:state.earned.includes(a.days)}))});window.dispatchEvent(new CustomEvent("gei:achievements-ready",{detail:{...state}}));loadVault();}
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init,{once:true});else init();
})();
