/* V1.20 — GEI Quick Access & Pop-Out Intelligence */
(() => {
  "use strict";
  const CONFIG = [
    ["gei-profile-card", "👤", "PROFILE", "LEARNER PROFILE", "Blueprint Identity"],
    ["gei-xp-card", "⭐", "XP", "XP INTELLIGENCE", "Learner Evolution"],
    ["gei-streak-card", "🎁", "MOMENTUM", "LEARNING MOMENTUM", "0 Day Streak"],
    ["gei-achievement-card", "🏆", "REWARDS", "STREAK ACHIEVEMENTS", "Learning Rewards"],
    ["gei-vault-card", "🔐", "VAULT", "LEARNER IDENTITY", "Achievement Vault"]
  ];
  const getHome=()=>document.getElementById("screen-home");
  const getStack=()=>{const h=getHome();return h?.querySelector(".home-experience-stack")||h?.querySelector(".dashboard-main");};
  const hide=c=>{c.hidden=true;c.setAttribute("aria-hidden","true");c.style.setProperty("display","none","important");};
  const show=c=>{c.hidden=false;c.removeAttribute("aria-hidden");c.style.removeProperty("display");};
  function buildRail(){const h=getHome(),s=getStack();if(!h||!s)return;let r=h.querySelector("#gei-quick-access");if(!r){r=document.createElement("div");r.id="gei-quick-access";r.setAttribute("role","toolbar");r.setAttribute("aria-label","GEI quick access");s.insertBefore(r,s.firstChild);}CONFIG.forEach(([id,icon,label])=>{if(r.querySelector(`[data-gei-popout="${id}"]`))return;const b=document.createElement("button");b.type="button";b.className="gei-quick-button";b.dataset.geiPopout=id;b.setAttribute("aria-label",`Open ${label}`);b.innerHTML=`<span class="gei-quick-icon" aria-hidden="true">${icon}</span><span class="gei-quick-label">${label}</span>`;r.appendChild(b);});CONFIG.forEach(([id])=>{const c=document.getElementById(id);if(c&&!c.closest(".gei-popout-backdrop"))hide(c);});}
  function close(trigger){const back=document.querySelector(".gei-popout-backdrop"),content=back?.querySelector(".gei-popout-content"),card=content?.querySelector("section[id^=gei-]");if(!back||!card)return;const s=getStack();if(s){show(card);s.appendChild(card);}back.remove();buildRail();trigger?.focus();}
  function open(id,trigger){if(document.querySelector(".gei-popout-backdrop"))close();const card=document.getElementById(id),h=getHome(),item=CONFIG.find(x=>x[0]===id);if(!card||!h||!item)return;const back=document.createElement("div");back.className="gei-popout-backdrop";const dialog=document.createElement("section");dialog.className="gei-popout-dialog";dialog.setAttribute("role","dialog");dialog.setAttribute("aria-modal","true");dialog.setAttribute("aria-labelledby","gei-popout-title");const closeButton=document.createElement("button");closeButton.type="button";closeButton.className="gei-popout-close";closeButton.setAttribute("aria-label","Close pop-out");closeButton.textContent="×";const content=document.createElement("div");content.className="gei-popout-content";const header=document.createElement("div");header.className="gei-popout-header";header.innerHTML=`<span class="gei-popout-icon" aria-hidden="true">${item[1]}</span><span class="gei-popout-kicker">${item[3]}</span><h2 id="gei-popout-title">${item[3]}</h2><span class="gei-popout-subtitle">${item[4]}</span>`;show(card);content.append(header,card);dialog.append(closeButton,content);back.appendChild(dialog);h.appendChild(back);const previous=document.activeElement;const onKey=e=>{if(e.key==="Escape"){e.preventDefault();cleanup();}};const cleanup=()=>{document.removeEventListener("keydown",onKey);close(previous?.isConnected?previous:null);};closeButton.addEventListener("click",cleanup);back.addEventListener("click",e=>{if(e.target===back)cleanup();});document.addEventListener("keydown",onKey);closeButton.focus();}
  function route(e){const b=e.target.closest?.("[data-gei-popout]");if(!b)return;e.preventDefault();e.stopPropagation();open(b.dataset.geiPopout,b);}
  function init(){if(document.querySelector('link[data-gei-quick-access-css]'))return;const link=document.createElement("link");link.rel="stylesheet";link.href="quick-access.css";link.dataset.geiQuickAccessCss="true";document.head.appendChild(link);buildRail();document.addEventListener("click",route,true);const h=getHome();if(h)new MutationObserver(()=>{if(!document.querySelector(".gei-popout-backdrop"))buildRail();}).observe(h,{childList:true,subtree:true});}
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init,{once:true});else init();
})();
